version: "3.3"

services:
  api:
    depends_on:
      - postgres
    build: .
    container_name: api
    networks:
      - aboba_network
    hostname: api
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_HOST=postgres_my_life
      - POSTGRES_PORT=5432
      - POSTGRES_DB=taskstore
      - POSTGRES_USER=go_user
      - POSTGRES_PASSWORD=8246go
    restart: on-failure

  postgres:
    image: postgres:14
    container_name: postgres_my_life
    networks:
      - aboba_network
    hostname: postgres_my_life
    environment:
      - POSTGRES_DB=taskstore
      - POSTGRES_USER=go_user
      - POSTGRES_PASSWORD=8246go
    volumes:
      - postgres_storage:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.domain/1_init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U go_user -domain taskstore"]
      interval: 10s
      timeout: 45s
      retries: 3
    restart: on-failure

  mongo:
    image: mongo:latest
    container_name: mongo_my_life
    networks:
      - aboba_network
    hostname: mongo_my_life
    environment:
      - MONGO_INITDB_ROOT_USERNAME=go_user
      - MONGO_INITDB_ROOT_PASSWORD=8246go
    restart: on-failure


volumes:
  postgres_storage:

networks:
  aboba_network:
    driver: bridge