name: sample_workflow
on:
    push:
        branches:
        - dev
        - main
jobs:
    build_api:
        runs-on: ubuntu-latest
        steps:
        # This step checks out a copy of your repository.
            - name: checkout
              uses: actions/checkout@v3
              
            - name: Setup Go environment
              uses: actions/setup-go@v3.0.0
              with:
                go-version: 1.18.1
                check-latest: false
            - run: go version
    run_tests:
        needs: build_api
        runs-on: ubuntu-latest
